### ISSUE TITLE
Fix access problems

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/ITLab-Salary#7]
Когда пользователь делает запрос на получение списка назначенных зарплат по его отчётам, он получает не только свои зарплаты, но и зарплаты других людей

**Comment by CAPCHIK** [comment]
Какая именно url?

**Comment by IvLaptev** [comment]
/api/salary/v1/report/user/<user_id>

**Comment by Suput** [comment]
@CAPCHIK @IvLaptev закрыто?

**Comment by CAPCHIK** [comment]
Да, все окей уже, это как раз та ситуация, где данные получаются при помощи пользовательского токена, чтобы не выдать ничего лишнего
